version: '3.4'

services:
  boynerapi:
    container_name: c_boynerapi
    image: ${DOCKER_REGISTRY-}boynerapi
    build:
      context: .
      dockerfile: Api/Dockerfile


  s_sqlserver:
    container_name: c_sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest

  s_redis:
    container_name: c_redis
    image: redis